ToruNiina/toml11

toml/parser.hpp
I spotted this when compiling on OS X. Linux seems fine, for some reason.
The sstringstream is used on line 92 of this file:
```cpp
static unsigned int make_codepoint(string_type str)
{
unsigned int codepoint;
std::basic_istringstream<value_type> iss(str);
iss >> std::hex >> codepoint;
return codepoint;
}
```
=> Fix missing include

tests/test_parse_unicode.cpp, toml/exception.hpp, toml/from_toml.hpp, toml/traits.hpp, toml/value.hpp
Intel C++ compiler is not completely standard compliant, but only a few changes are needed to make the code build and the tests pass.
I ran the tests locally with icc version 14.0.2.
Adding this compiler to travis is [possible](https://github.com/nemequ/icc-travis), but a bit hard: you need to apply for an open source license, and then renew the license every year.
=> Allow to build with intel c++ compiler

README.md, toml/value.hpp
In typical use cases, a user (actually, in this case, me) want to show an error message related to the value after successfully getting toml values. For example, users may need error messages in the case that an invalid value is specified, or a value conflicts with a value defined before.
It is good to have a function to show the error message related to toml::value.
=> enable to show user-defined error message with (a) toml::value(s)

tests/test_get.cpp, toml/get.hpp
In some cases, mostly with `toml::find`, we need to get an instance of `toml::value` to show a better error message.
```cpp
const auto  root = toml::parse(filename);
const auto& tab1 = toml::find<toml::table>(root, "table1", filename); // discarding region info
const auto& tab2 = toml::find<toml::table>(tab1, "table2", filename); // need filename
```
The above code shows an error message like the following when `table2` is missing.
```console
terminate called after throwing an instance of 'std::out_of_range'
what():  [error] key "table2" not found in example.toml
```
But `table2` is defined inside `table1`, so the error message should be
```console
terminate called after throwing an instance of 'std::out_of_range'
what():  [error] key "table2" not found
--> example.toml
3 | [table1]
| …
```
=> enable to get toml::value as toml::value

tests/CMakeLists.txt, tests/test_error_detection.cpp, toml/parser.hpp
This change makes toml11 to detect the case like the following.
```toml
table = [{a = 1.0}]
[[table]] # appending an array-of-tables to the existing array is invalid
a = 2.0
```
The error message looks like this.
```
terminate called after throwing an instance of 'toml::syntax_error'
what():  [error] toml::insert_value: array of table ("table") collides with existing array-of-tables
--> example.toml
1 | table = [{a = 1.0}]
|         ~~~~~~~~~~~ this array value has static size
...
2 | [[table]]
| ~~~~~~~~~ appending this to the statically sized array
```
Also, some other weird error messages that lack whitespaces are fixed.
Additionally, test code to check toml11 detects some kind of syntax errors is added.
=> improve error message quality

toml/parser.hpp
speed up `toml::prase` with long (in my case, thousands of lines of) toml files.
`format_underline` is a time-consuming function in the case of long toml files, and this PR removes the needless `format_underline` in `parse_*` functions and it makes the whole parsing process drastically faster.
=> speedup by removing needless format_underline

tests/test_parse_file.cpp, toml/parser.hpp
This PR fixes...
* finding and skipping BOM at the front of the file
* skipping lines at the end of a file that does not include newline but whitespaces
like:
```toml
key = "value"  # <- whitespace here
```
or
```toml
key = "value"
```
related to #16 .
=> fix the error with BOM and end of file w/o newline

toml/get.hpp
To get a nested table or to show an error message, `toml::find` is used with `toml::value`. It can be a default parameter because `toml::value` is a neutral type, in some sense.
=> add default template arg to toml::find

toml/value.hpp
It might be useful to have hints while writing an error message.
=> add an extra parameter `hints` to format_error

README.md, tests/test_parse_file.cpp, toml/parser.hpp
to avoid inconsistency between file size (obtained by `tellg`) and the
size of the actual contents that would be read later
Also, test cases that uses file are added.
=> fix: open file as binary-mode #16

toml/datetime.hpp
`std::localtime` is not thread safe, but it is used in toml11 to handle datetime classes.
This PR is to remove dependency on `std::localtime` and replace it with POSIX `localtime_r` or `localtime_s`, if it exists.
=> add threadsafe localtime_(s|r)

toml/parser.hpp
Following #27, this is a quick fix that changes the error message of the `parse_*` family of functions to show the location that they were given to parse.
=> Add location to error string in parse_* functions

tests/test_parse_key.cpp, toml/parser.hpp, toml/value.hpp
Error messages related to the dotted keys looks weird. like:
```
1 | a.b.c = 42
|         ~~ in this table
```
The underlined token is not a table. This should be like the following.
```
1 | a.b.c = 42
| ~~~ in this table
```
This PR improves this by using key-region information when constructing a table.
```
what():  [error] key "d" not found
--> test.toml
1 | a.b.c = 42
| ~~~~~ in this table
```
=> Error message for getting values corresponds to dotted keys

toml/lexer.hpp, toml/parser.hpp
- allow empty table
```toml
[empty.table]
[another.table]
```
- disallow key-after-table pattern
```toml
[table] key = "value" # INVALID
```
- fix lexer to allow only a valid escape sequence
=> small patches for parser

toml/parser.hpp, toml/value.hpp
Allow the following toml file.
```toml
[a.b.c]
d = 10
[a]
e = 2.718
```
It is equivalent to `a = {e=2.71800,b={c={d=10}}}`.
This change makes parser to allow also this.
```toml
a.b.c = {d = 10}
[a]
e = 2.718
```
because `a.b.c = {d = 10}` is equivalent to `a = {b = {c = {d = 10}}}`.
Still the following is not allowed.
```toml
[a]
b.c = {d = 10}
[a]
e = 2.718
```
Because `[a]` is defined twice.
```console
what(): [error] toml::insert_value: table ("a") already exists.
--> foo.toml
1 | [a]
| ~~~ table already exists here
...
4 | [a]
| ~~~ table defined twice
```
=> Allow deeper table before

toml/parser.hpp
The solution is not ideal, but it's okay at the line, I think
=> fix: suppress warning about sign-unsign comparison

toml/to_toml.hpp, toml/utility.hpp
because the constructor of `toml::value()` supports all the stuff that
are supported by `to_toml`.
I will remove it in the next version, v2.2.0.
=> feat: mark to_toml as deprecated

README.md, tests/test_value.cpp, toml/value.hpp
These changes enable the following.
```cpp
toml::value v = /* ... */;
const bool b = v.is_boolean();
const bool i = v.is_integer();
//...
```
=> add `is_boolean` and other stuffs like that

README.md, tests/CMakeLists.txt, tests/test_extended_conversions.cpp, toml/from.hpp, toml/get.hpp, toml/into.hpp, toml/traits.hpp, toml/value.hpp
support conversions between `toml::value` and `class/struct`s defined outside of toml11.
=> extended conversions

toml/parser.hpp
the following codepoints are considered to be a syntax_error.
- [0xD800, 0xDFFF]
- larger than 0x10FFFF
=> Throw syntax_error when parser encounter an incorrect utf-8 codepoint

tests/test_get_related_func.cpp, toml/get.hpp, toml/traits.hpp, toml/utility.hpp
- improve overload resolution of `get_or(value, fallback)`
- add `toml::find_or(table, key, fallback)`
- `toml::get_or(table, key, fallback)` is now deprecated
=> fix `get_or` and add `find_or`

toml/serializer.hpp
`toml::format()` formats a value, so `toml::table` might be encoded as an inline table.
Using this results an incorrect toml file.
```cpp
std::cout << "a = " << toml::format(toml::table{{"a", 42}, {"b", "c"}});
// a = {a=42,b="c"}
std::cout << toml::format(toml::table{{"a", 42}, {"b", "c"}});
// {a=42,b="c"}
```
This PR introduces an extra argument to `toml::format` to control this behavior.
```cpp
std::cout << toml::format(toml::table{{"a", 42}, {"b", "c"}});
// a = 42
// b = "c"
std::cout << toml::format(toml::table{{"a", 42}, {"b", "c"}},
/*width*/ 80, /*prec*/ 6, /*force_inline*/ true);
// {a=42, b="c"}
```
=> `toml::format` and top-level table

toml/combinator.hpp, toml/literal.hpp, toml/parser.hpp, toml/region.hpp
For parsing large files, like a file having tens of thousands of lines, it takes some minutes. It is intolerably slow (for me).
By profiling the parser, I found the hotspot and fixed the problem. This improves the runtime efficiency.
=> Speedup parsing large files

README.md, tests/test_literals.cpp, toml/literal.hpp
```cpp
"[1,2,3]"_toml;   // This is an array
"[table]"_toml;   // This is a table that has an empty table named "table" inside.
"[[1,2,3]]"_toml; // This is an array of arrays
"[[table]]"_toml; // This is a table that has an array of tables inside.
"[[1]]"_toml;     // This is ambiguous.
// Currently, it becomes a table that has an array of table named "1".
"1 = [{}]"_toml;  // This is a table that has an array of table named "1".
"[[1,]]"_toml;    // This is an array of arrays.
"[[1],]"_toml;    // ditto.
```
=> fix: resolve ambiguity in the `""_toml` literal

toml/literal.hpp, toml/region.hpp
- skip empty lines at the beginning of toml literal
- if toml literal is used with C++11 raw string literals, it may start with empty lines like the following.
```cpp
// there is a newline after `u8R"(` and
// it becomes an empty line at the beginning of literal.
const auto v = u8R"(
[table]
key = "value"
)"_toml;
```
- skip this empty line to show a meaningful part of a literal in the error message.
- avoid too long underline
- since `toml::detail::region::size()` returns a length of the whole region, a region that corresponds to a literal returns the length of whole literal. The region makes underline too long.
- use the shortest one between a length of a region or a length of a line shown there.
=> Improve error message from toml literal

README.md, tests/CMakeLists.txt, tests/test_comments.cpp, toml/region.hpp, toml/value.hpp
This provides a way to extract comments that are related to a `toml::value`.
It does not add any `std::string` member variables but member functions to `toml::value`. It does not have any impact on memory usage.
Note that this PR does not provide a way to preserve comments in the serialized file or to change comments related to a `toml::value`.
=> Preserve comments

README.md
The example code for converting between toml values and arbitrary types does not compile because `toml::from<T>::from_toml` and `toml::into<T>::into_toml` are not static. I'm assuming they're meant to be static because the unit test [here](https://github.com/ToruNiina/toml11/blob/master/tests/test_extended_conversions.cpp#L38-L57) has them written that way.
This partially addresses #83, however I am not sure whether or not it is intended that **both**  `toml::from` and `toml::into` need be specialized before you can use `toml::find` with arbitrary types.
=> Update documentation for toml::from and toml::into

toml/traits.hpp
Intel C++ Compiler 18.0.5 outputs the following warning:
```
toml11/toml/traits.hpp(108): warning #14: extra text after expected end of preprocessing directive
#undef decltype(...)
^
```
This PR fixes the above.
=> Suppress warning on Intel C++ Compiler

toml/serializer.hpp
This fixes the warning "compiler may not enforce left-to-right evaluation order for call to" that is caused by Visual Studio if this is compiled with a target of C++17.
I have a [branch at my fork](https://github.com/ToruNiina/toml11/compare/master...SeverinLeonhardt:fix_msvc_c4866_with_tests) with test cases to demonstrate the warning. As [documented by Microsoft](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4866?view=vs-2019) this warning only applies when compiling with `/std:c++17` which I just hacked in for demonstration purposes. If you prefer to have such test cases please let me know how to handle the requirement to compile for C++17.
=> Fix MSVC warning C4866

README.md
In #72, the include path in README has been changed from `<toml11/toml.hpp>` to `<toml.hpp>`, but there is still an example of including `<toml11/toml.hpp>`.
This PR fix it.
=> Fix include path in README

toml/comments.hpp, toml/source_location.hpp
Add includes required by code in a couple of individual headers, allowing them to be included directly again.
=> Add missing standard includes

README.md, toml/parser.hpp, toml/value.hpp
Without a region, error messages in exceptions are unable to print
a filename.
By retaining the location in a zero-length region and detecting this
when formatting the exception text it is possible to print the filename
and explicitly state that the file is completely empty.
Fixes #160
=> Preserve empty location for empty files

toml/serializer.hpp
Due to serializer constructor:
```c++
serializer(const std::size_t w              = 80u,
const int         float_prec     = std::numeric_limits<toml::floating>::max_digits10,
const bool        can_be_inlined = false,
const bool        no_comment     = false,
std::vector<toml::key> ks        = {},
const bool     value_has_comment = false)
: can_be_inlined_(can_be_inlined), no_comment_(no_comment),
value_has_comment_(value_has_comment && !no_comment),
float_prec_(float_prec), width_(w), keys_(std::move(ks))
{}
```
`can_be_inlined` should be the third param and `no_comment` should be the fourth param, but in `format` function, it has wrong order:
```c++
const auto serialized = visit(serializer<value_type>(w, fprec, no_comment, false), v);
```
=> fix: serializer has wrong constructor params order when format root object

toml/parser.hpp
As described in issue #173, this warning is raised on various platforms and in various build types. For example, g++ 11 in release mode will cause this warning to be raised. This change fixes this warning.
=> Resolve g++ warning: free-nonheap-object

CMakeLists.txt
When adding this library as embedded library with private "target link", e.g., only used inside private source files, the library does not need to be installed when the main project gets installed.
This adds an additional option `toml11_INSTALL` similar to the test-build control switch in order to skip installing headers and CMake config files if requested.
Avoids using
```cmake
add_subdirectory(path/to/toml11 EXCLUDE_FROM_ALL)
```
which has further side-effects:
https://cmake.org/cmake/help/v3.0/command/add_subdirectory.html
=> CMake: Optional Install if Embedded

README.md, toml/source_location.hpp
toml11 prints error messages with the `[error]` prefix by default.
Defining `TOML11_NO_ERROR_PREFIX` will let toml11 omit the prefix regardless of colorized or not in case you would use a custom prefix, such as `Error:`.
```cpp
#define TOML11_NO_ERROR_PREFIX
```
---
Without `TOML11_NO_ERROR_PREFIX`:
```console
[error] value should be positive
--> example.toml
3 | num = -42
|       ~~~ positive number required
```
With `TOML11_NO_ERROR_PREFIX`:
```console
value should be positive
--> example.toml
3 | num = -42
|       ~~~ positive number required
```
We are now able to customize the prefix like:
```cpp
fmt::print("Error: {}", e.what());
```
This prints out:
```console
Error: value should be positive
--> example.toml
3 | num = -42
|       ~~~ positive number required
```
=> Support opting out of the default `[error]` prefix

README.md, toml/color.hpp, toml/source_location.hpp
That `TOML11_COLORIZE_ERROR_MESSAGE` cannot change color mode at runtime is not useful when we want to accept arguments from users. Considering supporting the `--color` option on my command line application, I would implement it like:
```cpp
std::vector<std::string> args(argv + 1, argv + argc);
auto result = std::find(args.begin(), args.end(), "--color");
if (result != args.end()) {
// enable colorization
} else {
// disable colorization
}
```
For such cases, I implemented functions that allow users to control the color mode by just calling these functions.
```cpp
toml::color::enable();  // enable colorization
toml::color::disable(); // disable colorization
```
When we want to know the current color mode, call the `should_color` function:
```cpp
if (toml::color::should_color()) {
// ...
} …
```
=> Support changing color mode at runtime

toml/parser.hpp
Taking this parameter by const reference forces us to copy it (because
we know we're going to store it). Taking it by r-value reference would
suggest that we _might_ take ownership over it and would also force the
user to make a copy if they wish to retain the original value.
Taking this parameter by value however clearly gives us ownership of its
content without forcing a copy if it's implicit conversion from
`const char*` or explicitly handed over to us by the user via std::move.
Also note that without this the `std::move` call already present in `parse`
is effectively a NOP. (I.e. it calls the *const* r-value ref constructor of
`std::string`, which doesn't exist, so falls back to const l-value ref.).
=> fix: don't force a copy of std::string fname when moving is an option

tests/test_parse_file.cpp, toml/exception.hpp, toml/lexer.hpp, toml/parser.hpp
The `fstream` classes are notorious for their non-existent error handling. The stream error bits weren't even checked in the code, resulting in arbitrary malfunctions or crashing in case of an error.
This replaces the `ifstream` with C-style file IO (`fopen()`, etc.) and adds an exception class that is thrown in case of errors, including a descriptive error message.
It preserves the `parse()` variant for an istream, though I'd say using it with an ifstream is for the large part detrimental.
I'm introducing a new `file_io_error` exception class, let me know if it needs adjusting. It inherits from `std::runtime_error`, not from `toml::exception`, as that didn't seem to be a good fit. On a side note I think the whole exception class hierarchy should inherit from `std::runtime_error`, mainly …
=> Use C-style IO instead of ifstream for parsing

.editorconfig, toml/parser.hpp
This is my first PR; thanks for considering it!  It includes minor cleanup items.
- Add an [EditorConfig](https://editorconfig.org) file to set up editors for what appear to be the standards of the codebase (four-space indents in C++, two-space indents in md/yaml)
- Some error messages in the parser printed the wrong function names.  Fix those.
=> Add .editorconfig; fix some error messages in the parser

toml/parser.hpp
=> Fix address-sanitizer error when parsing literal strings having invalid UTF-8 characters

.github/workflows/main.yml
Updates  *checkout* v2 action – which uses [deprecated NodeJS 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) – to v3.
=> Update checkout action to v3

toml/region.hpp
We are using patched libc++ which uses raw pointers for vector itrators to improve code compilation speed. This commit fixed two compilation issues in toml11:
* location::const_iterator deinition assumes that vector const_iterator is struct or class type rather than raw pointer.
* `const const_itetr foo()` triggers `-Wignored-qualifiers` for primitive types and `void` which breaks `-Wextra -Werror` compilation.
=> Fix for case when vector iterator is raw pointer

CMakeLists.txt
According to [CMake 3.27 release notes](https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features):
> Compatibility with versions of CMake older than 3.5 is now deprecated and will be removed from a future version.
=> Require CMake 3.5+

README.md
Just a little help for newcomers to use the library without hassle.
=> Add installation example with checkinstall and cmake

toml/serializer.hpp
Previously a key like:
"a\u0000\u0001b" = 1
Would get written with literal control characters, rather than escapes:
"a<00><01>b" = 1
The "valid/key/quoted-unicode" test from toml-test would fail with this, although it seems they're not run automatically(?)
Can also reproduce with something like:
% cat test.cpp
#include <toml.hpp>
#include <iostream>
int main()
{
const auto data  = toml::parse("test.toml");
std::cout << data << "\n";
return 0;
}
% cat test.toml
"a\u0000\u0001b" = "a\u0000\u0001b"
% c++ -I. test.cpp
% ./a.out
"ab" = "a\u0000\u0001b"
% ./a.out | hexdump -C
00000000  22 61 00 01 62 22 20 3d  20 22 61 5c 75 30 30 30  |"a..b" = "a\u000|
00000010  30 5c 75 30 30 30 31 62  22 0a 0a                 |0\u0001b"..|
=> Escape control characters in keys

tests/test_parse_array.cpp, tests/test_parse_aux.hpp, tests/test_parse_inline_table.cpp, toml/literal.hpp, toml/parser.hpp
to avoid stack overflow caused by recursive function call, detected in fuzzing test
=> Limit value recursion

.github/workflows/main.yml, toml/exception.hpp
Link issue #231
It's possible a fix for #231 . But I still have no idea why _GNU_SOURCE is defined in something like Havoc.
=> fix issue #231 

cmake/toml11Config.cmake.in
I was trying to use this with vcpkg and encountered issues described in #110 . I've simply applied the changes described in this comment: https://github.com/ToruNiina/toml11/issues/110#issuecomment-917493436
Tested this locally with an overlay-port and was able to build using toml11 as a vcpkg port.'
I won't pretend to know exactly why this was an issue. I'm new to using vcpkg and CMake in general, just know that the fix described in the comment has worked and I did the legwork of applying and testing locally with vcpkg.
=> Fix issues with CMake package configuration when used with vcpkg #110

include/toml11/parser.hpp
Fix for issue #252 
Parser now checks for a carriage return when removing the newline at the end of a line comment, and if present removes it as well.
=> Fix not checking for \r\n when parsing line comments

include/toml11/traits.hpp, include/toml11/value.hpp, single_include/toml.hpp, tests/test_user_defined_conversion.cpp
Add a `has_template_into_toml_member` trait to support constructing or assigning to toml::basic_value with template `into_toml` method, as in the [doc](https://toruniina.github.io/toml11/docs/features/value/#defining-into_toml-member-function) and Issue #255.
=> Support template into_toml members (Issue #255)

include/toml11/parser.hpp
When reading a file to vector, manually cast the file size (represented as `std::streamoff` hidden as `auto`) to `std::streamsize`, which is the type for `std::istream::read()`; this avoids the warning/error
```
error: conversion from ‘long long int’ to ‘std::streamsize’ {aka ‘int’} may change value [-Werror=conversion]
```
This means a truncation happens on 32bit architectures, however that seems a limitation of the standard library.
=> fix: manually cast file size to std::streamsize

include/toml11/conversion.hpp, include/toml11/version.hpp, tests/test_user_defined_conversion.cpp
This PR enables support for `std::optional` members for `TOML11_DEFINE_CONVERSION_NON_INTRUSIVE`.  If a user-defined struct has a `std::optional` member and a TOML value doesn't have the key, the key-value will be `std::nullopt`. Similarly, if the struct's member holds `std::nullopt`, the conversion to TOML value will not include the key-value.
```cpp
struct my_toml
{
int a;
std::optional<int> b;
};
TOML11_DEFINE_CONVERSION_NON_INTRUSIVE(my_toml, a, b)
const toml::value v = toml::parse_str("a = 42");
const auto foo = toml::get<my_toml>(v);
assert(foo.a == 42);
assert(!foo.b.has_value());
```
=> Support std::optional members for TOML11_DEFINE_CONVERSION_NON_INTRUSIVE

include/toml11/fwd/color_fwd.hpp
closes: https://github.com/ToruNiina/toml11/issues/259
I used `TOML11_USE_THREAD_LOCAL_COLORIZATION` instead of `TOML11_THREAD_LOCAL_COLORIZATION` for the switch, as I think this is clearer.
=> Make thread_local for color_mode optional

docs/content.en/docs/features/value.md, docs/content.ja/docs/features/value.md
Remove the extra < in template syntax
=> Fix typos in documentation template syntax

CMakeLists.txt
The minimum required CMake version is 3.16 but CMP0127 was only introduced in 3.22. This results in errors with versions 3.16 - 3.21:
```
CMake Error at CMakeLists.txt:28 (cmake_policy):
Policy "CMP0127" is not known to this version of CMake.
```
Fixed by only setting the policy when it's actually available.
=> Fix use with CMake 3.21 and older

include/toml11/impl/source_location_impl.hpp
prevent an issue, where a string was created with size_t(0)-1 length.
When creating underlines for error output, the current column sometimes had cases where it was set to 0 caused an underflow.
Solves Issue #275
=> fix: prevent size_t-max length string allocation

include/toml11/result.hpp
The original code incorrectly accepts cv-qualified void types for success.
=> Use is_void<T> instead of is_same<T, void>

include/toml11/fwd/literal_fwd.hpp, include/toml11/impl/literal_impl.hpp
Clang 20+ errors about this whitespace.
Fixes
include/toml11/impl/../fwd/literal_fwd.hpp:22:26: error: identifier '_toml' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
|    22 | ::toml::value operator"" _toml(const char* str, std::size_t len);
|       |               ~~~~~~~~~~~^~~~~
|       |               operator""_toml
=> Remove whitespace in operator""

docs/content.en/docs/reference/parser.md
=> `third` arg -> `second` arg in `parser.md/istream parse`

docs/content.en/docs/reference/get.md
=> `条件` -> `condition` in `docs/get.md`

include/toml11/get.hpp, include/toml11/traits.hpp, tests/test_get.cpp
Easier than calling `toml::get<std::vector<T>>` then having to convert it to `std::unordered_set`
As part of the PR I added a couple of basic tests. They are mostly for demonstrating that this works.
=> add support for `toml::get<std::unordered_set>`
